import sys

with open('public/index.html', 'r', encoding='utf-8') as f:
    html = f.read()

# 1. Update addStuRule to support Scripting
old_add_rule = """    function addStuRule() {
      const m = allMocks.find(x => x.id === currentMockId);
      const rule = {
        name: prompt('Rule Name:', 'If API Key Missing'),
        conditions: [{ source: 'header', key: 'Authorization', operator: 'not_exists', value: '' }],
        response: { status_code: 401, body: { status:'error', message:'Unauthorized' } }
      };
      if (!m.rules) m.rules = [];
      m.rules.push(rule);
      renderStuRules(m.rules);
      toast('Rule added localy. Save to publish.');
    }"""

new_add_rule = """    function addStuRule(type = 'basic') {
      const m = allMocks.find(x => x.id === currentMockId);
      let rule;
      
      if (type === 'script') {
        const script = prompt('Enter JavaScript condition (req variable is available):', 'req.body.age < 18');
        if (!script) return;
        rule = {
          name: 'Script: ' + (script.length > 20 ? script.substring(0, 20) + '...' : script),
          conditions: [{ source: 'script', key: 'js', operator: 'script', value: script }],
          response: { status_code: 400, body: { status:'error', message:'Script Condition Met' } }
        };
      } else {
        rule = {
          name: prompt('Rule Name:', 'If API Key Missing'),
          conditions: [{ source: 'header', key: 'X-API-Key', operator: 'not_exists', value: '' }],
          response: { status_code: 401, body: { status:'error', message:'Unauthorized' } }
        };
      }
      
      if (!m.rules) m.rules = [];
      m.rules.push(rule);
      renderStuRules(m.rules);
      toast('Rule added locally. Save to publish.');
    }"""

html = html.replace(old_add_rule, new_add_rule)

# 2. Add Scripting buttons to the UI
old_rule_header = """                    <button class="btn btn-sm btn-secondary" onclick="addStuRule()">+ Add Rule</button>"""
new_rule_header = """                    <div style="display:flex; gap:8px">
                      <button class="btn btn-sm btn-secondary" onclick="addStuRule('basic')">+ Add Rule</button>
                      <button class="btn btn-sm btn-emerald" style="background:#10b981; color:white; border:none" onclick="addStuRule('script')">💻 Add Script Rule</button>
                    </div>"""

html = html.replace(old_rule_header, new_rule_header)

# 3. Add Script Body Helper
old_body_header = """                      <button class="btn btn-sm btn-secondary" onclick="prettifyMockBody()">Prettify JSON</button>"""
new_body_header = """                      <div style="display:flex; gap:8px">
                        <button class="btn btn-sm btn-emerald" style="background:#10b981; color:white; border:none" onclick="convertBodyToScript()">💻 Make Programmable</button>
                        <button class="btn btn-sm btn-secondary" onclick="prettifyMockBody()">Prettify JSON</button>
                      </div>"""

html = html.replace(old_body_header, new_body_header)

# 4. Add convertBodyToScript JS function
js_target = """    function prettifyMockBody() {"""
js_addition = """    function convertBodyToScript() {
      const val = qs('#s-body').value;
      if (val.startsWith('// script')) return;
      qs('#s-body').value = `// script\\nreturn {\\n  status: "success",\\n  time: new Date().toISOString(),\\n  message: "Generated by script",\\n  originalPayload: req.body\\n};`;
      toast('Body converted to Script');
    }

""" + js_target
html = html.replace(js_target, js_addition)

with open('public/index.html', 'w', encoding='utf-8') as f:
    f.write(html)
